import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from '@react-oauth/google';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="594421143248-ovd591e9dtc06qlb3up8nlkgt5dfo0os.apps.googleusercontent.com">
      <body className={inter.className}>{children}</body>
      </GoogleOAuthProvider>
    </html>
  );
}
